language: node_js
node_js:
  - node

install:
  - npm i -g serverless
  - npm install --no-optional

cache:
  - directories: node_modules
    
script:
  - chmod +x ./travis-deploy/deploy.sh
  - ./travis-deploy/deploy.sh
