service: users

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:us-east-1:*:*

functions:
  getAll:
    handler: getAll.handler
    events:
      - http:
          path: users
          method: get
          integration: lambda
  getByGroup:
    handler: getByGroup.handler
    events:
      - http:
          path: groups/{id}/users
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UserGroupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserGroup
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: groupId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: groupId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
