service:
  name: santaswap-api

plugins:
  - serverless-plugin-iopipe
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    IOPIPE_LOGGER_ENABLED: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
