service:
  name: santaswap-api

plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-plugin-iam-checker
  - serverless-cloudformation-resource-counter
  - serverless-stack-output
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  stage: personal
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:UpdateItem
      Resource:
        - { Fn::GetAtt: [GroupsTable, Arn] }
        - { Fn::Join: ['', [{ Fn::GetAtt: [GroupsTable, Arn] }, '/index/*']] }
  environment:
    TEST_REQUEST_HEADER: SantaSwap-Test-Request
    GROUPS_TABLE: { Ref: GroupsTable }
    GROUPS_TABLE_TYPE_INDEX: TypeIndex
    GROUPS_TABLE_CODE_INDEX: GroupCodeIndex
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${opt:stage, self:provider.stage}

custom:
  epsagon:
    token: ${env:EPSAGON_TOKEN}
    appName: ${self:service.name}-${opt:stage, self:provider.stage}
  stageProperties:
    default:
      enabled: false
      basePath: ${self:provider.stage}
    prod:
      enabled: true
      basePath: ''
  # Stupdily named (and stupidly not namespaced) property for the stack output serverless plugin
  output: { file: infrastructure/.stack-outputs.yml }
  customDomain:
    # basePath: ${self:custom.stageProperties.${opt:stage, self:provider.stage}.basePath, self:custom.stageProperties.default.basePath}
    stage: ${opt:stage, self:provider.stage}
    domainName: api.santaswap.io
    certificateName: '*.santaswap.io'
    enabled: ${self:custom.stageProperties.${opt:stage, self:provider.stage}.enabled, self:custom.stageProperties.default.enabled}

functions:
  createAndJoinGroup:
    handler: app/groups/create-and-join.handler
    events:
      - http:
          method: post
          path: users/{userId}/groups
          cors: true
          request:
            parameters:
              paths:
                userId: true

  joinGroup:
    handler: app/groups/join.handler
    events:
      - http:
          method: post
          path: groups/{groupId}/users/{userId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
                groupId: true

  updateProfile:
    handler: app/profiles/update-profile.handler
    events:
      - http:
          method: put
          path: groups/{groupId}/users/{userId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
                groupId: true

  excludeUser:
    handler: app/profiles/exclude-user.handler
    events:
      - http:
          method: post
          path: groups/{groupId}/users/{userId}/excludedUsers/{excludedUserId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
                groupId: true
                excludedUserId: true

  getAllGroupsByUser:
    handler: app/groups/get-all-by-user.handler
    events:
      - http:
          method: get
          path: users/{userId}/groups
          cors: true
          request:
            parameters:
              paths:
                userId: true

  getGroupDetailsByUser:
    handler: app/groups/get-detailed-by-user.handler
    events:
      - http:
          method: get
          path: users/{userId}/groups/{groupId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
                groupId: true

  matchGroup:
    handler: app/groups/match.handler
    events:
      - http:
          method: post
          path: users/{userId}/groups/{groupId}/match
          cors: true
          request:
            parameters:
              paths:
                groupId: true
                userId: true

resources:
  Resources:
    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: recordExpiration
          Enabled: true
        GlobalSecondaryIndexes:
          - IndexName: TypeIndex
            KeySchema:
              - AttributeName: type
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: GroupCodeIndex
            KeySchema:
              - AttributeName: code
                KeyType: HASH
            Projection:
              ProjectionType: ALL
