service:
  name: santaswap-api

plugins:
  - serverless-plugin-iopipe
  - serverless-webpack
  - serverless-plugin-iam-checker

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: { Fn::GetAtt: [GroupsTable, Arn] }
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    IOPIPE_LOGGER_ENABLED: true
    GROUPS_TABLE: { Ref: GroupsTable }

functions:
  createGroup:
    handler: groups/create.handler
    events:
      - http:
          method: get
          path: hello
          cors: true

resources:
  Resources:
    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
