swagger: '2.0'
info:
  description: 'API for the Santa Swap app'
  version: '0.0.1'
  title: 'Santa Swap API'
  x-logo:
    url: 'https://user-images.githubusercontent.com/2955468/50532511-363a6d80-0ae8-11e9-80db-31bc2ca211b7.png'
    backgroundColor: '#FAFAFA'
    altText: 'Santa Swap API logo'

tags:
  - name: 'Group setup'
    description: 'Creating and joining games'

paths:
  /users:
    post:
      tags:
        - Group setup
      summary: 'Create user'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'NewUserRequest'
          description: 'Properties of the new user being created'
          required: true
          schema:
            $ref: '#/definitions/NewUserRequest'
      responses:
        200:
          description: 'User successfully created'
          schema:
            $ref: '#/definitions/UserResponse'

  /users/{userId}/groups:
    post:
      tags:
        - Group setup
      summary: 'Create and join group'
      description: 'Creates a new group and adds the specified user to that group'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userId'
          in: 'path'
          description: 'ID of the user creating the group (who will be added to the newly created group)'
          required: true
          type: 'string'
        - in: 'body'
          name: 'NewGroupRequest'
          description: 'Properties of the new group being created'
          required: true
          schema:
            $ref: '#/definitions/NewGroupRequest'
      responses:
        200:
          description: 'Group successfully created and user added'
          schema:
            $ref: '#/definitions/GroupResponse'

    get:
      tags:
        - Group setup
      summary: 'Get groups by users'
      description: 'Gets all groups that a user has been added to'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userId'
          in: 'path'
          description: 'ID of the user to get groups by'
          required: true
          type: 'string'
      responses:
        200:
          description: 'Group successfully created and user added'
          schema:
            $ref: '#/definitions/SimpleGroupResponse'

  /groups/{groupId}/users/{userId}:
    post:
      tags:
        - Group setup
      summary: 'Join group'
      description: 'Creates a new group and adds the specified user to that group'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'groupId'
          in: 'path'
          description: 'ID of the group the user will join'
          required: true
          type: 'string'
        - name: 'userId'
          in: 'path'
          description: 'ID of the user joining the group'
          required: true
          type: 'string'
      responses:
        200:
          description: 'User successfully added to group'
          schema:
            $ref: '#/definitions/GroupResponse'

  /users/{userId}/groups/{groupId}:
    get:
      tags:
        - Group setup
      summary: 'Get group detail by user'
      description: 'Creates a new group and adds the specified user to that group'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userId'
          in: 'path'
          description: 'ID of the user to get group details for (response changes by requesting user)'
          required: true
          type: 'string'
        - name: 'groupId'
          in: 'path'
          description: 'ID of the group to get details for'
          required: true
          type: 'string'
      responses:
        200:
          description: 'Group successfully created and user added'
          schema:
            $ref: '#/definitions/DetailedGroupResponse'

definitions:
  NewUserRequest:
    type: 'object'
    properties:
      name:
        type: 'string'
        description: "User's name"

  UserResponse:
    type: 'object'
    properties:
      userId:
        type: 'string'
      name:
        type: 'string'
        description: "User's name"

  NewGroupRequest:
    type: 'object'
    properties:
      name:
        type: 'string'
        description: "Group's name"

  SimpleGroupResponse:
    type: 'object'
    properties:
      groupId:
        type: 'string'
      name:
        type: 'string'
        description: 'Name of the group'
      members:
        type: 'array'
        description: 'Names of the people in the group'
        items:
          type: 'string'

  DetailedGroupResponse:
    type: 'object'
    properties:
      groupId:
        type: 'string'
      code:
        type: 'string'
        description: 'Code for joining this group'
      name:
        type: 'string'
        description: 'Name of the group'
      profile:
        $ref: '#/definitions/Profile'
      members:
        type: 'array'
        description: 'Names of the people in the group'
        items:
          $ref: '#/definitions/UserResponse'

  Profile:
    type: 'object'
    properties:
      profileId:
        type: 'string'
      name:
        type: 'string'
      excludedUserIds:
        type: 'array'
        items:
          type: 'string'

  GroupResponse:
    type: 'object'
    properties:
      groupId:
        type: 'string'
      code:
        type: 'string'
        description: 'Code for joining this group'
      name:
        type: 'string'
        description: 'Name of the group'
